### ISSUE TITLE
Add installation for macOS

### ISSUE THREAD

**Issue by ademaro** [deponian/logalize#3]
If there are no specific dependencies, it would be great to add a package for macos users to install from homebrew.

**Comment by deponian** [comment]
Hi! I'm not familiar with Homebrew and macOS ecosystem in general, but I'll see what I can do

**Comment by deponian** [comment]
Logalize isn't yet ready to be added to the main `homebrew-core` repository because we have less than 75 stars. I've created my own Homebrew tap, so now you can install Logalize on macOS like this: `brew install deponian/tap/logalize`

**Comment by deponian** [comment]
Logalize isn't yet ready to be added to the main `homebrew-core` repository because we have less than 75 stars. See details [here](https://github.com/Homebrew/homebrew-core/pull/197757)

I've created my own Homebrew tap, so now you can install Logalize on macOS like this: `brew install deponian/tap/logalize`

**Comment by federico-ntr** [comment]
Sorry for necro-posting, but since the repo has now more than 100 stars, maybe you can try the PR again(?)

**Comment by deponian** [comment]
Sorry, but to be honest, I don't really see the point. In my opinion, there isn't much difference between `brew install logalize` and `brew install deponian/tap/logalize`.

When it comes to my own tap, it's much easier for me to release new versions on my own and not have to rely on anyone else :)
